apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'api-gateway'
        metrics_path: /metrics
        static_configs:
          - targets: ['api-gateway:80']

      - job_name: 'scheduler'
        metrics_path: /metrics
        static_configs:
          - targets: ['scheduler:80']

      - job_name: 'gpu-workers'
        metrics_path: /metrics
        static_configs:
          - targets: ['gpu-worker-spot:80', 'gpu-worker-dedicated:80']
